"""Precomputed library of combat NPC stat blocks.

The world generator and hydration layer call ``get_archetype(name)`` to
fetch a fresh ``NPCStatBlock`` for a common combat opponent. Each builder
returns a new instance so that mutable state (``uses_remaining``, phase
flags) is not shared between encounters.

This library is deliberately narrow: it covers the tiers and roles needed
by the current combat system. Unique villains have their stat blocks
generated by the arc generator (task 42), not this library.
"""

from collections.abc import Callable

from engine.inventory import DamageType
from engine.npc_stat_block import (
    BehaviorProfile,
    LegendaryAction,
    NPCAttack,
    NPCStatBlock,
    NPCTier,
    PhaseTransition,
    SignatureAbility,
    SignatureAbilityEffect,
)


# ---------------------------------------------------------------------------
# Minion builders
# ---------------------------------------------------------------------------


def _build_commoner() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.MINION,
        archetype="commoner",
        multiattack_count=1,
        attacks=[
            NPCAttack(
                name="Club",
                damage_dice="1d4",
                damage_type=DamageType.BLUDGEONING,
                to_hit_bonus=1,
            ),
        ],
        behavior_profile=BehaviorProfile.DEFENSIVE,
        aggression_threshold=18,
    )


def _build_guard() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.MINION,
        archetype="guard",
        multiattack_count=1,
        attacks=[
            NPCAttack(
                name="Spear",
                damage_dice="1d6+1",
                damage_type=DamageType.PIERCING,
                to_hit_bonus=3,
                range_type="reach",
            ),
        ],
        behavior_profile=BehaviorProfile.DEFENSIVE,
        aggression_threshold=14,
    )


def _build_bandit() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.MINION,
        archetype="bandit",
        multiattack_count=1,
        attacks=[
            NPCAttack(
                name="Scimitar",
                damage_dice="1d6+1",
                damage_type=DamageType.SLASHING,
                to_hit_bonus=3,
            ),
            NPCAttack(
                name="Light Crossbow",
                damage_dice="1d8+1",
                damage_type=DamageType.PIERCING,
                to_hit_bonus=3,
                range_type="ranged",
                range_value=80,
            ),
        ],
        behavior_profile=BehaviorProfile.AGGRESSIVE,
        aggression_threshold=12,
    )


def _build_cultist() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.MINION,
        archetype="cultist",
        multiattack_count=1,
        attacks=[
            NPCAttack(
                name="Ritual Dagger",
                damage_dice="1d4+1",
                damage_type=DamageType.PIERCING,
                to_hit_bonus=3,
            ),
        ],
        behavior_profile=BehaviorProfile.AGGRESSIVE,
        aggression_threshold=10,
    )


# ---------------------------------------------------------------------------
# Elite builders
# ---------------------------------------------------------------------------


def _build_soldier() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.ELITE,
        archetype="soldier",
        multiattack_count=2,
        attacks=[
            NPCAttack(
                name="Longsword",
                damage_dice="1d8+3",
                damage_type=DamageType.SLASHING,
                to_hit_bonus=5,
            ),
        ],
        signature_abilities=[
            SignatureAbility(
                name="Shield Wall",
                description="Grants +2 AC to adjacent allies for 1 round.",
                usage="per_combat",
                uses_remaining=1,
                action_cost="bonus",
                effects=[
                    SignatureAbilityEffect(
                        kind="buff",
                        condition_duration_rounds=1,
                        target_scope="all_allies_in_zone",
                    ),
                ],
            ),
        ],
        behavior_profile=BehaviorProfile.DEFENSIVE,
        aggression_threshold=13,
    )


def _build_captain() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.ELITE,
        archetype="captain",
        multiattack_count=2,
        attacks=[
            NPCAttack(
                name="Longsword",
                damage_dice="1d8+3",
                damage_type=DamageType.SLASHING,
                to_hit_bonus=5,
            ),
        ],
        signature_abilities=[
            SignatureAbility(
                name="Rally",
                description=(
                    "Heals nearby allies for 1d8+3 and removes Frightened."
                ),
                usage="per_combat",
                uses_remaining=1,
                effects=[
                    SignatureAbilityEffect(
                        kind="heal",
                        dice="1d8+3",
                        target_scope="all_allies_in_zone",
                    ),
                ],
            ),
        ],
        behavior_profile=BehaviorProfile.SUPPORT,
        aggression_threshold=12,
    )


def _build_brute() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.ELITE,
        archetype="brute",
        multiattack_count=2,
        attacks=[
            NPCAttack(
                name="Greatclub",
                damage_dice="2d6+4",
                damage_type=DamageType.BLUDGEONING,
                to_hit_bonus=6,
            ),
        ],
        signature_abilities=[
            SignatureAbility(
                name="Reckless Charge",
                description=(
                    "Moves one zone and attacks with advantage; attacks "
                    "against the brute have advantage until its next turn."
                ),
                usage="per_combat",
                uses_remaining=1,
                effects=[
                    SignatureAbilityEffect(
                        kind="move",
                        target_scope="self",
                    ),
                    SignatureAbilityEffect(
                        kind="damage",
                        dice="2d6+4",
                        damage_type=DamageType.BLUDGEONING,
                        target_scope="single",
                    ),
                ],
            ),
        ],
        behavior_profile=BehaviorProfile.AGGRESSIVE,
        aggression_threshold=10,
    )


def _build_mage() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.ELITE,
        archetype="mage",
        multiattack_count=2,
        attacks=[
            NPCAttack(
                name="Fire Bolt",
                damage_dice="2d10",
                damage_type=DamageType.FIRE,
                to_hit_bonus=6,
                range_type="ranged",
                range_value=120,
            ),
        ],
        signature_abilities=[
            SignatureAbility(
                name="Counterspell",
                description=(
                    "Reaction: cancels a spell of level 3 or lower cast "
                    "within range."
                ),
                usage="per_combat",
                uses_remaining=1,
                is_reaction=True,
                action_cost="reaction",
                effects=[
                    SignatureAbilityEffect(
                        kind="debuff",
                        target_scope="single",
                    ),
                ],
            ),
        ],
        behavior_profile=BehaviorProfile.TACTICAL,
        aggression_threshold=11,
    )


def _build_assassin() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.ELITE,
        archetype="assassin",
        multiattack_count=2,
        attacks=[
            NPCAttack(
                name="Shortsword",
                damage_dice="1d6+4",
                damage_type=DamageType.PIERCING,
                to_hit_bonus=6,
            ),
        ],
        signature_abilities=[
            SignatureAbility(
                name="Death Strike",
                description=(
                    "Automatic critical hit against a Surprised target, "
                    "once per combat."
                ),
                usage="per_combat",
                uses_remaining=1,
                effects=[
                    SignatureAbilityEffect(
                        kind="damage",
                        dice="4d6+4",
                        damage_type=DamageType.PIERCING,
                        target_scope="single",
                    ),
                ],
            ),
        ],
        behavior_profile=BehaviorProfile.TACTICAL,
        aggression_threshold=10,
    )


def _build_shaman() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.ELITE,
        archetype="shaman",
        multiattack_count=2,
        attacks=[
            NPCAttack(
                name="Quarterstaff",
                damage_dice="1d6+2",
                damage_type=DamageType.BLUDGEONING,
                to_hit_bonus=4,
            ),
        ],
        signature_abilities=[
            SignatureAbility(
                name="Spirit Guardians",
                description=(
                    "Concentration: 2d8 radiant damage to enemies entering "
                    "the shaman's zone."
                ),
                usage="per_combat",
                uses_remaining=1,
                effects=[
                    SignatureAbilityEffect(
                        kind="aoe_damage",
                        dice="2d8",
                        damage_type=DamageType.RADIANT,
                        target_scope="zone",
                    ),
                ],
            ),
        ],
        behavior_profile=BehaviorProfile.SUPPORT,
        aggression_threshold=12,
    )


# ---------------------------------------------------------------------------
# Boss fallback builder
# ---------------------------------------------------------------------------


def _build_generic_boss() -> NPCStatBlock:
    return NPCStatBlock(
        tier=NPCTier.BOSS,
        archetype="generic_boss",
        multiattack_count=3,
        attacks=[
            NPCAttack(
                name="Dread Blade",
                damage_dice="2d6+4",
                damage_type=DamageType.SLASHING,
                to_hit_bonus=7,
            ),
        ],
        signature_abilities=[
            SignatureAbility(
                name="Terrifying Shout",
                description=(
                    "All enemies in range must make a WIS save or become "
                    "Frightened for 2 rounds."
                ),
                usage="per_combat",
                uses_remaining=1,
                effects=[
                    SignatureAbilityEffect(
                        kind="condition",
                        condition_name="Frightened",
                        condition_duration_rounds=2,
                        save_ability="WIS",
                        save_dc=15,
                        target_scope="all_enemies",
                    ),
                ],
            ),
            SignatureAbility(
                name="Dark Surge",
                description="Unleashes necrotic energy on a single target.",
                usage="per_combat",
                uses_remaining=2,
                effects=[
                    SignatureAbilityEffect(
                        kind="damage",
                        dice="4d8",
                        damage_type=DamageType.NECROTIC,
                        target_scope="single",
                    ),
                ],
            ),
            SignatureAbility(
                name="Lifedrain",
                description="Heals self by draining an enemy's vitality.",
                usage="per_combat",
                uses_remaining=1,
                effects=[
                    SignatureAbilityEffect(
                        kind="heal",
                        dice="3d8",
                        target_scope="self",
                    ),
                ],
            ),
        ],
        legendary_actions=[
            LegendaryAction(
                name="Quick Strike",
                cost=1,
                description="Makes one melee attack as a legendary action.",
                effects=[
                    SignatureAbilityEffect(
                        kind="damage",
                        dice="2d6+4",
                        damage_type=DamageType.SLASHING,
                        target_scope="single",
                    ),
                ],
            ),
            LegendaryAction(
                name="Menace",
                cost=2,
                description="Forces a WIS save or inflict Frightened.",
                effects=[
                    SignatureAbilityEffect(
                        kind="condition",
                        condition_name="Frightened",
                        condition_duration_rounds=1,
                        save_ability="WIS",
                        save_dc=14,
                        target_scope="single",
                    ),
                ],
            ),
            LegendaryAction(
                name="Shadow Step",
                cost=3,
                description="Teleports to an adjacent zone and attacks.",
                effects=[
                    SignatureAbilityEffect(kind="move", target_scope="self"),
                    SignatureAbilityEffect(
                        kind="damage",
                        dice="2d6+4",
                        damage_type=DamageType.SLASHING,
                        target_scope="single",
                    ),
                ],
            ),
        ],
        legendary_points_per_round=3,
        phases=[
            PhaseTransition(
                trigger_hp_percent=66,
                narrative_cue="The boss's eyes burn with fresh malice.",
                attack_bonus=1,
            ),
            PhaseTransition(
                trigger_hp_percent=33,
                narrative_cue=(
                    "The boss unleashes its full fury, desperation etched on "
                    "its face."
                ),
                attack_bonus=2,
                save_bonus=2,
            ),
        ],
        behavior_profile=BehaviorProfile.TACTICAL,
        aggression_threshold=8,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


ARCHETYPE_BUILDERS: dict[str, Callable[[], NPCStatBlock]] = {
    "commoner": _build_commoner,
    "guard": _build_guard,
    "bandit": _build_bandit,
    "cultist": _build_cultist,
    "soldier": _build_soldier,
    "captain": _build_captain,
    "brute": _build_brute,
    "mage": _build_mage,
    "assassin": _build_assassin,
    "shaman": _build_shaman,
    "generic_boss": _build_generic_boss,
}


def get_archetype(name: str) -> NPCStatBlock:
    """Return a fresh stat block for the named archetype.

    Raises:
        KeyError: If the archetype name is not in ``ARCHETYPE_BUILDERS``.
            Callers must either guard with ``name in ARCHETYPE_BUILDERS``
            or catch the exception and default to ``commoner``.
    """
    return ARCHETYPE_BUILDERS[name]()


def list_archetypes() -> list[str]:
    """Return the sorted list of archetype names available in this library."""
    return sorted(ARCHETYPE_BUILDERS.keys())
