"""Story arc domain model.

Represents the narrative plan for a campaign — a sequence of story beats
from introduction through resolution.
"""

from typing import Literal

from pydantic import BaseModel, Field

from engine.npc_stat_block import NPCStatBlock


class CompletionTrigger(BaseModel):
    """Deterministic condition for beat completion."""

    type: Literal["interact", "defeat", "talk", "arrive", "search", "pickup"]
    target: str


class BeatEffects(BaseModel):
    """World mutations applied when a beat is completed."""

    unlock_exits: list[str] = Field(default_factory=list)
    add_npcs: list[str] = Field(default_factory=list)
    remove_items: list[str] = Field(default_factory=list)
    add_items: list[str] = Field(default_factory=list)
    state_flags: dict[str, bool] = Field(default_factory=dict)
    narrative_hint: str = ""


class StoryBeat(BaseModel):
    """One narrative step in the campaign arc."""

    beat_number: int = Field(ge=1, le=20)
    title: str = Field(min_length=1)
    description: str
    location_hint: str
    npc_names: list[str] = Field(default_factory=list)
    encounter_type: Literal["social", "combat", "exploration", "puzzle", "boss"]
    encounter_subtype: str | None = None
    is_twist: bool = False
    completion_trigger: CompletionTrigger | None = None
    on_complete: BeatEffects = Field(default_factory=BeatEffects)


class StoryArc(BaseModel):
    """Complete narrative arc for a campaign."""

    campaign_id: str
    theme: str
    premise: str = Field(min_length=10)
    beats: list[StoryBeat] = Field(min_length=8, max_length=20)
    current_beat_index: int = Field(default=0, ge=0)
    villain_name: str
    villain_motivation: str
    villain_stat_block: NPCStatBlock | None = None
    """Full combat stat block for the villain, generated by the arc
    generator at the same moment it invents the villain's narrative.
    ``None`` for legacy arcs — the hydration layer (task 43) falls back
    to ``engine.npc_library.get_archetype('generic_boss')`` in that case.
    """


def advance_beat(arc: StoryArc) -> StoryArc:
    """Return a new StoryArc with current_beat_index incremented.

    Idempotent at the last beat — returns unchanged arc.
    """
    if arc.current_beat_index >= len(arc.beats) - 1:
        return arc
    return arc.model_copy(update={"current_beat_index": arc.current_beat_index + 1})
