"""Story arc domain model.

Represents the narrative plan for a campaign — a sequence of story beats
from introduction through resolution.
"""

from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field, model_validator

from engine.npc_stat_block import NPCStatBlock


class CompletionTrigger(BaseModel):
    """Deterministic condition for beat completion."""

    type: Literal["interact", "defeat", "talk", "arrive", "search", "pickup"]
    target: str


class ObjectiveKind(str, Enum):
    """Type of player action a BeatObjective listens for."""

    TALK = "talk"
    DEFEAT = "defeat"
    ARRIVE = "arrive"
    EXAMINE = "examine"
    POSSESS = "possess"
    FLAG = "flag"
    # New values to cover all legacy CompletionTrigger.type literals
    INTERACT = "interact"
    SEARCH = "search"
    PICKUP = "pickup"


class GateKind(str, Enum):
    """Additional mechanical condition layered on top of an ObjectiveKind match."""

    MIN_REVEALS = "min_reveals"
    MIN_DISPOSITION = "min_disposition"
    HAS_ITEM = "has_item"
    FLAG_SET = "flag_set"


class ObjectiveGate(BaseModel):
    """A post-match constraint on an objective."""

    kind: GateKind
    value: int | str


class BeatObjective(BaseModel):
    """A verifiable condition that contributes to beat completion."""

    id: str = Field(min_length=1)
    kind: ObjectiveKind
    target: str = Field(min_length=1)
    description: str = Field(min_length=1)
    required: bool = True
    fuzzy_threshold: float = Field(default=0.7, ge=0.0, le=1.0)
    gate: ObjectiveGate | None = None


class AdvanceRule(str, Enum):
    """How objective completion combines into beat completion."""

    ALL_REQUIRED = "all_required"
    ANY = "any"
    M_OF_N = "m_of_n"


class BeatEffects(BaseModel):
    """World mutations applied when a beat is completed."""

    unlock_exits: list[str] = Field(default_factory=list)
    add_npcs: list[str] = Field(default_factory=list)
    remove_items: list[str] = Field(default_factory=list)
    add_items: list[str] = Field(default_factory=list)
    state_flags: dict[str, bool] = Field(default_factory=dict)
    narrative_hint: str = ""


class StoryBeat(BaseModel):
    """One narrative step in the campaign arc."""

    beat_number: int = Field(ge=1, le=20)
    title: str = Field(min_length=1)
    description: str
    location_hint: str
    npc_names: list[str] = Field(default_factory=list)
    encounter_type: Literal["social", "combat", "exploration", "puzzle", "boss"]
    encounter_subtype: str | None = None
    is_twist: bool = False

    # NEW: structured objectives (replaces single completion_trigger)
    objectives: list[BeatObjective] = Field(default_factory=list)
    advance_rule: AdvanceRule = AdvanceRule.ALL_REQUIRED
    advance_threshold: int | None = None  # for AdvanceRule.M_OF_N
    player_visible_hint: str | None = None  # for /hint level 1
    judge_rubric: str | None = None  # for BeatJudge LLM context

    # Runtime progression state (H16): completed objective id → campaign
    # turn number when completed (None when unknown). Serialized in
    # arc_json with the rest of the beat — no DB schema change. Merged
    # back by BeatProgressionEngine.evaluate() so multi-action beats
    # (M_OF_N, ALL_REQUIRED across turns) accumulate progress instead of
    # recomputing from zero every turn.
    objectives_completed: dict[str, int | None] = Field(default_factory=dict)

    # LEGACY: kept for read-back compat, auto-migrated to `objectives` on load
    completion_trigger: CompletionTrigger | None = None
    on_complete: BeatEffects = Field(default_factory=BeatEffects)


class StoryArc(BaseModel):
    """Complete narrative arc for a campaign."""

    campaign_id: str
    theme: str
    premise: str = Field(min_length=10)
    situation: str = ""
    """Macro-context — what's happening in the world right now, without revealing
    the villain or the twist. Shown to players in the opening crawl embed.
    Empty on legacy arcs; the embed skips the field when empty."""
    call_to_action: str = ""
    """Initial hook — why the party is drawn into this story, written in second-
    person plural ("vous"). Represents the apparent objective (may be a red
    herring or deliberately vague). Never reveals the villain or the twist."""
    beats: list[StoryBeat] = Field(min_length=8, max_length=20)
    current_beat_index: int = Field(default=0, ge=0)
    villain_name: str
    villain_motivation: str
    villain_stat_block: NPCStatBlock | None = None
    """Full combat stat block for the villain, generated by the arc
    generator at the same moment it invents the villain's narrative.
    ``None`` for legacy arcs — the hydration layer (task 43) falls back
    to ``engine.npc_library.get_archetype('generic_boss')`` in that case.
    """

    @model_validator(mode="after")
    def _migrate_legacy_completion_triggers(self) -> "StoryArc":
        """Convert legacy `completion_trigger` to a single `BeatObjective` per beat.

        Triggered automatically on every StoryArc construction (load from DB or
        in-memory). Only runs on beats whose `objectives` list is empty.
        Trigger types not mappable to ObjectiveKind are silently skipped.

        TALK triggers get an automatic ``MIN_REVEALS >= 2`` gate so a beat
        doesn't advance the moment the player says hello to the right NPC —
        the conversation must reveal at least two pieces of substance. Other
        kinds (defeat/arrive/pickup/interact/search/examine/possess/flag) are
        self-validating: the action either happened or it didn't.
        """
        valid_kinds = {k.value for k in ObjectiveKind}
        for beat in self.beats:
            if beat.objectives:
                continue  # explicit objectives win
            ct = beat.completion_trigger
            if ct is None or ct.type not in valid_kinds:
                continue
            kind = ObjectiveKind(ct.type)
            # Default gate by kind — protects against trivial-validation bugs
            # where saying "hi" to the right NPC instantly advances the beat.
            default_gate: ObjectiveGate | None = None
            if kind == ObjectiveKind.TALK:
                default_gate = ObjectiveGate(kind=GateKind.MIN_REVEALS, value=2)
            beat.objectives = [
                BeatObjective(
                    id=f"legacy_{ct.type}_{ct.target}",
                    kind=kind,
                    target=ct.target,
                    description=f"{ct.type} {ct.target}",
                    required=True,
                    gate=default_gate,
                ),
            ]
        return self


def advance_beat(arc: StoryArc) -> StoryArc:
    """Return a new StoryArc with current_beat_index incremented.

    Idempotent at the last beat — returns unchanged arc.
    """
    if arc.current_beat_index >= len(arc.beats) - 1:
        return arc
    return arc.model_copy(update={"current_beat_index": arc.current_beat_index + 1})
